### PR TITLE
Switch from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by emmahsax**
Switch from Travis CI to GitHub Actions. This will join a slow shift in Jekyll's projects from Travis CI to GitHub Actions.

I also prefer to use GitHub Actions because Travis CI (at least on travis-ci.com) is now charging money for users to use more than 10K credits.

### CODE REVIEW

**Comment by emmahsax** [comment]
@parkr or @DirtyF or @ashmaroli 

I've created this pull request to help move this repository from Travis CI to GitHub Actions. Can you please take a look when you have a chance?

I also don't know how to make my pull request trigger GitHub Actions workflows... that may be a setting in the repository, but they all passed on [my fork's pull request](https://github.com/emmahsax/jekyll-sitemap/pull/9) except the Rubocop test.

**Comment by ashmaroli** [comment]
@emmahsax Thank you for initiating the migration.
The reason your workflow did not trigger a run on this repo is probably because of:
- There wasn't an existing workflow file on the default branch here.
- Your workflow is in a fork. (Technically, not part of this repo yet).
- Your first contribution here. (Unlikely a reason, but possible).

I have now pushed a workflow file to `master`, to have GH Actions recognize pull requests from forks to this repo.
Please rebase your branch along with the following changes:
- The `if: "!contains(github.event.commits[0].message, '[ci skip]')"` is no longer necessary. GH Actions have it built-in now.
- You need not configure new jobs. Keep it DRY (as much as possible) using `matrix.include`. Refer [Jekyll core CI workflow](https://github.com/jekyll/jekyll/blob/master/.github/workflows/ci.yml) for an example.
- Default checkout depth is fine. 1000 commits deep is ....
- Matrix entry `3.0` needs to be quoted `"3.0"`. So quote all entries.
- Prefer double-quoted strings consistently.
- Leave out running RuboCop from the matrix for this pull request. The existing config is old. I'll update after merging your PR and CI is successfully online.

**Comment by emmahsax** [comment]
@ashmaroli Thank you for the response! I have made the suggestions you mentioned. I suppose I need approval to run workflows on this pull request, but then they should trigger 🤞🏼 .

Thank you!

**Comment by emmahsax** [comment]
@ashmaroli All right, the tests have all run and passed. This PR is ready for another review!

**Review by ashmaroli — APPROVED** [review]

**Comment by ashmaroli** [comment]
Thank you @emmahsax 
@jekyllbot: merge +dev

**Pull request merged**
