### PR TITLE
Change readme usage add to _config gems as array

### PR DESCRIPTION
**Pull request by surfer190**
Change Readme according to [Docs](http://jekyllrb.com/docs/configuration/#default-configuration)

### CODE REVIEW

**Comment by pathawks** [comment]
Why is this better? Seems less readable if you have many gems.

**Comment by parkr** [comment]
I agree with @pathawks here. Thanks for the PR though!!

**Comment by surfer190** [comment]
Just looking out for the new user, as I received:

`found character that cannot start any token while scanning for the next token`

with:

```
gems:
                 - jekyll-sitemap
````

The space is a single default vim tab, and not 4 spaces. When it was 4 spaces it worked, just something that may deter potential first time yaml users

**Comment by pathawks** [comment]
Yes, it might be wise to make sure it is clear that YAML needs to be indented with spaces rather than tabs.

**Comment by surfer190** [comment]
Yeah, not purveyed well but I guess I wasn't actively searching for it...(yaml faq)[http://yaml.org/faq.html]

**Pull request closed without merging**
