### PR TITLE
Docs: set site.url in config

### LINKED ISSUE #156: sitemap.xml always points to github?
Looking at the local output of my sitemap.xml, I see it is generating links for `http://<user>.github.io/<repo>/<rest of url ...>`

Should the sitemap.xml links not be `http://localhost:4000/<repo>/<rest of url ...>` (i.e. localhost when local, github.io when on github, etc.?)

(Having locally worked out the site superstructure, I have now gone in to _config.yml to set baseurl:\<repo> and am hunting down links I have now broken.)

I am left wondering, when I push the site to production at a non-github location, whether the sitemap.xml links will still point to github.

Could https://github.com/jekyll/jekyll-sitemap/blob/master/README.md be updated to document what sorts of links I should be seeing, where?

### LINKED ISSUE #171: Inform users that `url` is required in _config.yml
Great gem, thanks for making!

I battled an issue recently where my sitemap.xml links were invalid because they did not include the URL. The issue arose because I forgot to site the `url` parameter in my `_config.yml` file.

Granted I am a Jekyll newbie, but for the several Jekyll sites that I created and posted to Github, setting this parameter was not required, so I never filled it in.

Since it is required for this gem to work properly, would it be possible to update the README to state so?

Thanks.

### PR DESCRIPTION
**Pull request by jakob-stoeck**
fix #171 #156

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @jakob-stoeck! Can you describe what problem you're trying to solve? 

If it's that you need to add `site.url` to your config, I'd call that a configuration, not an installation instruction, and optional, since hosted services like GitHub Pages will set that automatically.

**Comment by jakob-stoeck** [comment]
@benbalter Hi Ben, agreed. But since two of the six issues addressed this problem (#156, #171) it doesn’t seem obvious for everybody.

With a standard Jekyll installation the `site.url` parameter is empty and everything works fine because the URL is not used anywhere. That is until you install a plugin which uses it, like the sitemap one.

**Comment by antgel** [comment]
It would be great to see this merged. Apparently I'm not the only one that fell into this trap.

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Pull request merged**
