### PR TITLE
Support per-page/post sitemap tags

### PR DESCRIPTION
**Pull request by kevinoid**
It would be nice if jekyll-sitemap could support setting sitemap tags on a per-page/post basis.  In particular, I would like to set `changefreq` and/or `priority` for particular pages.

This PR introduces support for per-page/post sitemap tags using the `sitemap.tags` property in the YAML frontmatter.  Since `sitemap` is already used to exclude pages, this name should be safe to use.  I chose the `tags` subproperty to avoid potential conflicts between any future per-page/post sitemap configuration and custom sitemap tags.

Thanks for considering,
Kevin

### CODE REVIEW

**Comment by benbalter** [comment]
@kevinoid thanks for the pull request. Can you explain a bit more about your reasoning for the pul request? What problem are you trying to solve? See https://github.com/jekyll/jekyll-sitemap/pull/33, https://github.com/jekyll/jekyll-sitemap/pull/21, and https://github.com/jekyll/jekyll-sitemap/issues/116 for some prior discussions on the topic.

**Comment by kevinoid** [comment]
@benbalter Sure.  My use case is to set a higher priority for the "main" pages on my site as a hint to search engines and archivers.  One example would be for them to be included in Google [Sitelinks](https://support.google.com/webmasters/answer/47334) or similar features of other search engine.

(What signals Google uses in its algorithm for Sitelinks is not public, so it may not be the best example, but is the sort of hint I'm trying to make to any sitemap consumer).

**Comment by pathawks** [comment]
My fear here is that we may be giving users just enough rope to hang themselves.

`changefreq` and `priority` should only be used in *very* limited circumstances. In general, search engines can figure this out on their own without any hints from webmasters.

I have seen naïve users set the `priority` of their blog homepage to be higher than the posts, even though there isn't really any original content on the homepage and blog posts are what should really be on search results pages.

I am of the mind that creating a sitemap from scratch is not difficult for power users, so this plugin should really focus on serving the needs of the most common use cases rather than trying to shoehorn in support for every power user feature.

I think we are better off *not* asking users to understand these extra configuration options.

**Comment by kevinoid** [comment]
@pathawks That's reasonable.  There are certainly power/complexity/potential for misuse tradeoffs.

If sitemap-aware crawlers can determine `changefreq` and `priority` better than the site administrator, they can probably also enumerate `url`s and mostly ignore declared `lastmod` times.  In that case, why bother maintaining a sitemap plugin at all?  If some sitemap consumers may benefit from the `url` and `lastmod` information, why not `changefreq` and `priority`?

I suspect search engines weigh search query, user history and prefs, and other metrics against the sitemap priority when choosing what to display.  So, although admins may mis-prioritize their pages (from some point of view), I don't see it as a catastrophic error.  But I could be wrong.  SEO is not my area of expertise.

I don't know all the uses of sitemap data, nor exactly how search engines use it, which makes concrete arguments difficult.  Specifying `changefreq` and `priority` clearly has some user interest, based on previous issues and comments, but we may all be mistaken.  It won't bother me if you are not interested in supporting it.  If you are, I can update the PR to include a warning about potential misuse of `changefreq`/`priority` if that is a significant concern.

**Comment by janpansa** [comment]
@pathawks We are trying to add priority to our pages, because search engines do not accurately list our pages. Pages that are really unimportant and almost never visited according to our analytics, and not even part of our main nav are placed higher in the search engine.

**Comment by jankovarik** [comment]
I just wanted to add my own request for ability to set a custom priority for certain pages in sitemap.xml, because it is important. By default, all pages have 50% priority, so you could keep it as a default vaule for all pages (unless specified otherwise) and let user set custom value for each page.

**Comment by DirtyF** [comment]
As discussed in previous issues, this plugin aims to be a set up and forget tool that generates a basic sitemap. Priorities and changefreq have been removed alltogether.
Search engines are more and more relying on `users` real world behavior to rank pages, not on on some webmasters and SEO trickery. If you  are looking for a customized sitemap, we encourage you to write your own XML template instead.

**Comment by jankovarik** [comment]
> As discussed in previous issues, this plugin aims to be a set up and forget tool that generates a basic sitemap. Priorities and changefreq have been removed alltogether.
> Search engines are more and more relying on `users` real world behavior to rank pages, not on on some webmasters and SEO trickery. If you are looking for a customized sitemap, we encourage you to write your own XML template instead (you can perfectly copy the current template and tailor it to your needs).

Ok, but just to be clear about "SEO trickery" you've mentioned - this is a real feature of XML sitemaps and it it's actually very useful and it has nothing to do with any "hacking" or misleading users. For example: my website is a brand new and has a new inner structure which search engine doesn't know yet and it's virtually impossible for it to say which sites are more important than others, etc. I'm just saying that this attribute is legit and can be significantly helpful, that's all.

**Comment by jayvdb** [comment]
I was using an enhanced sitemap so that I could injest that metadata from sibling sites into a parent/meta site.

**Pull request closed without merging**
