### PR TITLE
Remove `changefreq`

### PR DESCRIPTION
**Pull request by pathawks**
I'm sure this conflicts with #33

Once one is merged, I can rebase the other.

### CODE REVIEW

**Comment by sethladd** [comment]
It's bad (misleading) info. Can we remove? :)

**Comment by parkr** [comment]
I spent some time searching, and it looks like providing false information doesn't penalize us (i.e. if we say `weekly` and the data isn't changing weekly). All I can find online, actually, is documentation for what `changefreq` is, not how it should be used. What is the default that Google will use if nothing is specified? Will this be frequent enough? It seems like a good idea to err on the side of more frequent than less.

**Comment by erkki** [comment]
Agreed on no information being better than wrong information, have to keep in mind sitemap content is meant to be used relativistically inside a site not compared to other sites, so putting prio to 1 and changefreq to daily for all sites effectively means doing nothing, only way to semantically correctly provide these bits of information is to let the user provide them.

**Comment by pathawks** [comment]
> **Q:** Is there any point in submitting a Sitemap if all the metadata (<changefreq>, <priority>, etc.) is the same for each URL, or if I'm not sure it's accurate?
> **A:** If the value of a particular tag is the same for 100% of the URLs in your Sitemap, you don't need to include that tag in your Sitemap. Including it won't hurt you, but it's essentially the same as not submitting any information, since it doesn't help distinguish between your URLs. If you're not sure whether your metadata is accurate (for example, you don't know when a particular URL was last modified), it's better to omit that tag for that particular URL than to just make up a value which may be inaccurate.

http://googlewebmastercentral.blogspot.com/2008/01/sitemaps-faqs.html

**Comment by parkr** [comment]
I'm :+1: . @benbalter ?

**Comment by benbalter** [comment]
:shipit: Thanks @pathawks!

**Pull request merged**
