### PR TITLE
Docs: Mention front matter defaults

### LINKED ISSUE #192: exclude directories via config
Being able to exclude entire directories from being included in the sitemap would be a nice enhancement.

### PR DESCRIPTION
**Pull request by DirtyF**
fix #192

### CODE REVIEW

**Comment by COV-GIS** [comment]
This isn't working for me. Not an expert, but it appears as if `defaults` config are only injected if front matter is present. Using your example of pdf files, and html w/o front matter, they are still included in the sitemap with `defaults` config set.

If this is the case, and I'm not having another issue, you may want to note it will only work with front mattered files.

**Comment by DirtyF** [comment]
The example above will only work with Jekyll > 3.4.2. I could come up with another example.

**Comment by COV-GIS** [comment]
I'm on 3.4.3.

**Comment by DirtyF** [comment]
Thanks for the feedback, I took this example from [the official release 3.4.2 post](https://jekyllrb.com/news/2017/03/09/jekyll-3-4-2-released/), I thought it would work out of the box without the need to test it. 😕 

I reproduced this with latest 3.6: I can't exclude a PDF file. 
It works with a `.txt` file without YFM though, which is [the only test we have in our test suit](https://github.com/jekyll/jekyll/blob/229769e249bc9a6703fda4a9af061cd639d1ca75/test/test_static_file.rb#L144-L153).

I might be missing something here or it's an upstream bug

/cc @benbalter

**Comment by COV-GIS** [comment]
Thanks for looking into it and maintaining this plugin!

I switched up my workflow as a fix.

**Comment by benbalter** [comment]
> It works with a .txt file without YFM though, which is the only test we have in our test suit.

There **is** a test for front matter defaults being respected in PDFs! Proud to say I wrote it! :smile::

https://github.com/jekyll/jekyll/blob/5df6e3f8651e02879aca6c67edf35e5bf8081851/test/test_static_file.rb#L114-L122

Tested locally, and I was able to recreate the problem with the config you've documented, but was also able to resolve it by removing the trailing slash from the path.

See the example in https://jekyllrb.com/docs/configuration/#precedence, for the `projects/` folder, the path should be `projects`. 

I don't know if that's a bug, intuitive, or purposeful, but removing the trailing slash works locally for me.

**Comment by DirtyF** [comment]
@benbalter🎩  😄 

Should have looked twice 👁  👁  before speaking 😅 

Related: https://github.com/jekyll/jekyll/pull/6268

**Pull request closed without merging**
