### PR TITLE
Check default 'sitemap' for given static file

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
I think it would be better to replace extension matching to sitemap flag checking via defaults, yet that would break backward compatibility

**Comment by benbalter** [comment]
@alexey-pelykh to confirm, this is intended to implement excluding documents with `sitemap: false` in the front matter set via defaults? Isn't that being handled via https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml#L19? If not, we can use `to_liquid` to filter both explicit and implicit values in Ruby. Either way, we should add a (failing) test.

**Comment by alexey-pelykh** [comment]
@benbalter This was intended to exclude PDF & Word documents that are in static_files yet have no front matter at all, since it would be inconvenient to add that to binary files. We use this like
```
defaults:
  # Default:
  -
    values:
      layout: 'default'
  # Magnetic content
  -
    scope:
      path: 'content'
    values:
      sitemap: false
```

**Comment by benbalter** [comment]
Interesting. Can static files accept front matter defaults today (outside this plugin)?

**Comment by alexey-pelykh** [comment]
To my understanding, yes:
https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb#L138
https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb#L77

**Comment by benbalter** [comment]
@parkr compare https://github.com/jekyll/jekyll/blob/master/lib/jekyll/convertible.rb#L120-L121 with https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb#L98. Should static files get front matter defaults as part of the `to_liquid` method? Glad to put together a quick PR if so.

**Comment by parkr** [comment]
> Should static files get front matter defaults as part of the to_liquid method?

*Should* they? That's a very interesting question... generally speaking: no, but this use-case would make it seem like a good idea. Would you submit a PR to jekyll/jekyll that adds a new `StaticFileDrop` class and uses `Drops::StaticFileDrop.new(self)` for `to_liquid` instead of that hash? The key thing to implement is a `StaticFileDrop#fallback_data` method which doesn't munge site data.

**Comment by alexey-pelykh** [comment]
@benbalter I've added a test that covers "should be excluded" case

**Comment by parkr** [comment]
Jekyll v3.4.2 (released just a few moments ago) adds support for static files: https://github.com/jekyll/jekyll/pull/5941

**Comment by DirtyF** [comment]
See [example for excluding PDFs and such from sitemap](https://jekyllrb.com/news/2017/03/09/jekyll-3-4-2-released/).

@pathawks I guess you can close this issue.

**Pull request closed without merging**
